### ISSUE TITLE
Reader does not handle logrotate managed files

### ISSUE THREAD

**Issue by MidLifeXis** [melezhik/logdog#1]
Possibly a read-error on my part, but logrotate-style log files do not appear to be handled properly by this plugin.  The potential exists for a chunk of data to be missed if a logrotate event happens.

Scenario:

Period T between checks.  At T-1 second after the previous check, a logrotate event happens.  The current check only reads the last 1 seconds of data in the current log file.

**Comment by melezhik** [comment]
Hi Brain ! Thanks for using sparrow and logdog!

I can think about alternative data _source parameter in plugin configuration to express log entries sources not limited by a single find, something like that : 

```
    data_source : cat /var/log/auth.log; cat /var/log/auth-`date “+%Y-%m-%d”`; 
```

So data source could be a bash expression to produce output treated as log entries stream proceeded by plugin. 

Would it meet your requirements ?

**Comment by MidLifeXis** [comment]
Not really a requirement (not a sparrow user), but just a general bug note on the original implementation.  Seems like you have understood the issue.  Up to the users now if it works for them :-)

**Comment by melezhik** [comment]
sure, thanks for pointing this. as this is not a real request, closing this. But I guess I consider of improving this somehow .... :smile:
